routes/web.php
<?php

use App\Http\Controllers\CustomerController;
use App\Http\Controllers\RoleController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/dashboard',function(){
    return view('backend.hudai');
})->name('dashboard');
//for Roles
Route::group(['prefix'=>'roles','as'=>'roles.'], function(){
    Route::get('/', [RoleController::class, 'roleIndex'])->name('index');
    Route::get('/create', [RoleController::class, 'roleCreate'])->name('create');
    Route::post('/store', [RoleController::class, 'roleStore'])->name('store');
    Route::get('/show', [RoleController::class, 'roleShow'])->name('show');
    Route::get('/edit', [RoleController::class, 'roleEdit'])->name('edit');
    Route::patch('/update', [RoleController::class, 'roleUpdate'])->name('update');
    Route::patch('/delete', [RoleController::class, 'roleDestroy'])->name('destroy');
});

//for Customers
Route::group(['prefix'=>'customers','as'=>'customers.'], function(){
    Route::get('/', [CustomerController::class, 'customerIndex'])->name('index');
    Route::get('/create', [CustomerController::class, 'customerCreate'])->name('create');
    Route::post('/store', [CustomerController::class, 'customerStore'])->name('store');
    Route::get('/show', [CustomerController::class, 'customerShow'])->name('show');
    Route::get('/edit', [CustomerController::class, 'customerEdit'])->name('edit');
    Route::patch('/update', [CustomerController::class, 'customerUpdate'])->name('update');
    Route::patch('/delete', [CustomerController::class, 'customerDestroy'])->name('destroy');
});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $table='comments';
    public function customers(){
        return $this->belongsTo(Customer::class,'customer_id');
    }
    public function posts(){
        return $this->belongsTo(Post::class,'post_id');
    }
    public function replies(){
        return $this->hasMany(Reply::class,'comment_id');
    }
}

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $table='customers';
    
    public function role(){
        return $this->belongsTo(Role::class,'role_id');
    }
    public function posts(){
        return $this->hasMany(Post::class,'customer_id');
    }
    public function comments(){
        return $this->hasMany(Comment::class,'customer_id');
    }
    public function replies(){
        return $this->hasMany(Reply::class,'customer_id');
    }
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table='posts';

    public function customers(){
        return $this->belongsTo(Customer::class,'customer_id');
    }
    public function comments(){
        return $this->hasMany(Comment::class,'post_id');
    }
    public function replies(){
        return $this->hasMany(Reply::class,'post_id');
    }
}

app/Models/Reply.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Reply extends Model
{
    protected $table='replies';
    
    public function customers(){
        return $this->belongsTo(Customer::class,'customer_id');
    }
    public function comments(){
        return $this->belongsTo(Comment::class,'comment_id');
    }
    public function posts(){
        return $this->belongsTo(Post::class,'post_id');
    }
}

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $table='roles';

    public function customers(){
        return $this->hasMany(Customer::class,'role_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CustomerController extends Controller
{
    public function customerIndex(){
        return view('backend.customers.template');
    }
    public function customerShow(){
        return view('backend.customers.show');
    }

    public function customerCreate(){
        return view('backend.customers.create');
    }

    public function customerStore(){
        
    }

    public function customerEdit(){
        return view('backend.customers.edit');
    }

    public function customerUpdate(){

    }

    public function customerDestroy(){

    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    public function roleIndex(){
        return view('backend.roles.template');
    }
    public function roleShow(){
        return view('backend.roles.show');
    }

    public function roleCreate(){
        return view('backend.roles.create');
    }

    public function roleStore(Request $request){
        $request->validate([
            'roles_name' => 'required|string|max:255',
        ]);
        $role = new Role();
        $role->roles_name = $request->input('roles_name');
        $role->save();

        return redirect()->route('roles.index')->with('success', 'Role created successfully');
    }

    public function roleEdit(){
        return view('backend.roles.edit');
    }

    public function roleUpdate(){

    }

    public function roleDestroy(){

    }
}

resources/views/backend/customers/create.blade.php
<x-backend.layouts.master>
    create
</x-backend.layouts.master>

resources/views/backend/customers/edit.blade.php
<x-backend.layouts.master>
    edit
</x-backend.layouts.master>

resources/views/backend/customers/index.blade.php
<x-backend.layouts.master>
    index
</x-backend.layouts.master>

resources/views/backend/customers/show.blade.php
<x-backend.layouts.master>
  show
</x-backend.layouts.master>

resources/views/backend/customers/template.blade.php
<x-backend.layouts.master>

<div class="row clearfix dashboard-items">
    <div class="col-md-4">
        <div class="card p-2 shadow-sm  rounded-3">
            <div class="body text-center">
                <a href="{{ route('customers.index') }}" target="_blank">
                    <i class="fa-solid fa-address-book mt-3" style="font-size: 10em;"></i>
                    <h5 class="mt-2">Customers List</h5>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card p-2 shadow-sm  rounded-3">
            <div class="body text-center">
                <a href="{{ route('customers.show') }}" target="_blank">
                    <i class="fa fa-book mt-3" style="font-size: 10em;"></i>
                    <h5 class="mt-2">Customers Details</h5>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card p-2 shadow-sm  rounded-3">
            <div class="body text-center">
                <a href="{{ route('customers.create') }}" target="_blank">
                    <i class="fa-solid fa-file-pen mt-3" style="font-size: 10em;"></i>
                    <h5 class="mt-2">Create Customers</h5>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card p-2 shadow-sm  rounded-3">
            <div class="body text-center">
                <a href="{{ route('customers.edit') }}" target="_blank">
                    <i class="fa fa-pencil mt-3" style="font-size: 10em;"></i>
                    <h5 class="mt-2">Edit Customers</h5>
                </a>
            </div>
        </div>
    </div>
    {{-- <div class="col-md-4">
        <div class="card p-2 shadow-sm  rounded-3">
            <div class="body text-center">
                <a href="{{ route('customers.edit') }}" target="_blank">
                    <i class="fa-regular fa-pen-to-square mt-3" style="font-size: 10em;"></i>
                    <h5 class="mt-2">Role Update</h5>
                </a>
            </div>
        </div>
    </div> --}}
    <div class="col-md-8">
        <div class="card p-2 shadow-sm  rounded-3">
            <div class="body text-center">
                <a href="{{ route('customers.destroy') }}" target="_blank">
                    <i class="fa-regular fa-trash-can mt-3" style="font-size: 10em;"></i>
                    <h5 class="mt-2">Delete Customers</h5>
                </a>
            </div>
        </div>
    </div>
    {{-- <div class="col-md-3">
        <div class="card">
            <div class="body text-center">
                <a href="/studentportal/studentsPayable/show" target="_blank">
                    <i class="fa fa-hand-o-left" style="font-size: 10em;"></i>
                    <h5>Payable List</h5>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card">
            <div class="body text-center">
                <a href="/studentportal/studentsPayment/show" target="_blank">
                    <i class="fa fa-hand-o-right" style="font-size: 10em;"></i>
                    <h5>All Payments</h5>
                </a>
            </div>
        </div>
    </div> --}}
</div>
</x-backend.layouts.master>

resources/views/backend/hudai.blade.php
<x-backend.layouts.master>
    Hudai
</x-backend.layouts.master>

resources/views/backend/roles/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Limitless - Responsive Web Application Kit by Eugene Kopyov</title>

    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link href="{{ asset('ui/backend') }}/global_assets/css/icons/icomoon/styles.min.css" rel="stylesheet"
        type="text/css">
    <link href="{{ asset('ui/backend') }}/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="{{ asset('ui/backend') }}/assets/css/bootstrap_limitless.min.css" rel="stylesheet" type="text/css">
    <link href="{{ asset('ui/backend') }}/assets/css/layout.min.css" rel="stylesheet" type="text/css">
    <link href="{{ asset('ui/backend') }}/assets/css/components.min.css" rel="stylesheet" type="text/css">
    <link href="{{ asset('ui/backend') }}/assets/css/colors.min.css" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->

    <!-- Core JS files -->
    <script src="{{ asset('ui/backend') }}/global_assets/js/main/jquery.min.js"></script>
    <script src="{{ asset('ui/backend') }}/global_assets/js/main/bootstrap.bundle.min.js"></script>
    <script src="{{ asset('ui/backend') }}/global_assets/js/plugins/loaders/blockui.min.js"></script>
    <!-- /core JS files -->

    <!-- Theme JS files -->
    <script src="{{ asset('ui/backend') }}/global_assets/js/plugins/forms/styling/uniform.min.js"></script>

    <script src="{{ asset('ui/backend') }}/assets/js/app.js"></script>
    <script src="{{ asset('ui/backend') }}/global_assets/js/demo_pages/login.js"></script>
    <!-- /theme JS files -->

</head>

<body>

    <!-- Main navbar -->
    <div class="navbar navbar-expand-md navbar-dark">
        <div class="navbar-brand">
            <a href="index.html" class="d-inline-block">
                <img src="{{ asset('ui/backend') }}/global_assets/images/logo_light.png" alt="">
            </a>
        </div>

        <div class="d-md-none">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
                <i class="icon-tree5"></i>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="navbar-mobile">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a href="#" class="navbar-nav-link">
                        <i class="icon-display4"></i>
                        <span class="d-md-none ml-2">Go to website</span>
                    </a>
                </li>

                <li class="nav-item dropdown">
                    <a href="#" class="navbar-nav-link">
                        <i class="icon-user-tie"></i>
                        <span class="d-md-none ml-2">Contact admin</span>
                    </a>
                </li>

                <li class="nav-item dropdown">
                    <a href="#" class="navbar-nav-link">
                        <i class="icon-cog3"></i>
                        <span class="d-md-none ml-2">Options</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <!-- /main navbar -->


    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">
            <!-- Content area -->
            <div class="content d-flex justify-content-center align-items-center">
                <!-- Registration form -->
                <form action="{{ route('roles.store') }}" method="POST" enctype="multipart/form-data"
                    class="flex-fill">
                    @csrf
                    <div class="row">
                        <div class="col-lg-6 offset-lg-3">
                            <div class="card mb-0">
                                <div class="card-body">
                                    <div class="text-center mb-3">
                                        <i
                                            class="icon-plus3 icon-2x text-success border-success border-3 rounded-round p-3 mb-3 mt-1"></i>
                                        <h5 class="mb-0">Create Roles</h5>
                                        <span class="d-block text-muted">All fields are required</span>
                                    </div>

                                    <div class="form-group form-group-feedback form-group-feedback-right">
                                        <input type="text" name="roles_name" value="{{ old('role_name') }}"
                                            class="form-control" placeholder="Choose username">
                                        @error('roles_name')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                        @enderror
                                        <div class="form-control-feedback">
                                            <i class="icon-user-plus text-muted"></i>
                                        </div>
                                    </div>
                                    <button type="submit"
                                        class="btn bg-teal-400 btn-labeled btn-labeled-right w-100"><b><i
                                                class="icon-plus3"></i></b> Create Role</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- /registration form -->

            </div>
            <!-- /content area -->


            <!-- Footer -->
            <div class="navbar navbar-expand-lg navbar-light">
                <div class="text-center d-lg-none w-100">
                    <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse"
                        data-target="#navbar-footer">
                        <i class="icon-unfold mr-2"></i>
                        Footer
                    </button>
                </div>

                <div class="navbar-collapse collapse" id="navbar-footer">
                    <span class="navbar-text">
                        &copy; 2015 - 2018. <a href="#">Limitless Web App Kit</a> by <a
                            href="http://themeforest.net/user/Kopyov" target="_blank">Eugene Kopyov</a>
                    </span>

                    <ul class="navbar-nav ml-lg-auto">
                        <li class="nav-item"><a href="https://kopyov.ticksy.com/" class="navbar-nav-link"
                                target="_blank"><i class="icon-lifebuoy mr-2"></i> Support</a></li>
                        <li class="nav-item"><a href="http://demo.interface.club/limitless/docs/"
                                class="navbar-nav-link" target="_blank"><i class="icon-file-text2 mr-2"></i> Docs</a>
                        </li>
                        <li class="nav-item"><a
                                href="https://themeforest.net/item/limitless-responsive-web-application-kit/13080328?ref=kopyov"
                                class="navbar-nav-link font-weight-semibold"><span class="text-pink-400"><i
                                        class="icon-cart2 mr-2"></i> Purchase</span></a></li>
                    </ul>
                </div>
            </div>
            <!-- /footer -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</body>

</html>

resources/views/backend/roles/edit.blade.php
<x-backend.layouts.master>
    edit
</x-backend.layouts.master>

resources/views/backend/roles/index.blade.php
<x-backend.layouts.master>
    index
</x-backend.layouts.master>

resources/views/backend/roles/show.blade.php
<x-backend.layouts.master>
    show
</x-backend.layouts.master>

resources/views/backend/roles/template.blade.php
<x-backend.layouts.master>
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif
    <div class="row clearfix dashboard-items">
        <div class="col-md-4">
            <div class="card p-2 shadow-sm  rounded-3">
                <div class="body text-center">
                    <a href="{{ route('roles.index') }}" target="_blank">
                        <i class="fa-solid fa-address-book mt-3" style="font-size: 10em;"></i>
                        <h5 class="mt-2">Roles List</h5>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card p-2 shadow-sm  rounded-3">
                <div class="body text-center">
                    <a href="{{ route('roles.show') }}" target="_blank">
                        <i class="fa fa-book mt-3" style="font-size: 10em;"></i>
                        <h5 class="mt-2">Roles Details</h5>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card p-2 shadow-sm  rounded-3">
                <div class="body text-center">
                    <a href="{{ route('roles.create') }}" target="_blank">
                        <i class="fa-solid fa-file-pen mt-3" style="font-size: 10em;"></i>
                        <h5 class="mt-2">Roles Create</h5>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card p-2 shadow-sm  rounded-3">
                <div class="body text-center">
                    <a href="{{ route('roles.edit') }}" target="_blank">
                        <i class="fa fa-pencil mt-3" style="font-size: 10em;"></i>
                        <h5 class="mt-2">Roles Edit</h5>
                    </a>
                </div>
            </div>
        </div>
        {{-- <div class="col-md-4">
        <div class="card p-2 shadow-sm  rounded-3">
            <div class="body text-center">
                <a href="{{ route('roles.edit') }}" target="_blank">
                    <i class="fa-regular fa-pen-to-square mt-3" style="font-size: 10em;"></i>
                    <h5 class="mt-2">Role Update</h5>
                </a>
            </div>
        </div>
    </div> --}}
        <div class="col-md-8">
            <div class="card p-2 shadow-sm  rounded-3">
                <div class="body text-center">
                    <a href="{{ route('roles.destroy') }}" target="_blank">
                        <i class="fa-regular fa-trash-can mt-3" style="font-size: 10em;"></i>
                        <h5 class="mt-2">Roles Delete</h5>
                    </a>
                </div>
            </div>
        </div>
        {{-- <div class="col-md-3">
        <div class="card">
            <div class="body text-center">
                <a href="/studentportal/studentsPayable/show" target="_blank">
                    <i class="fa fa-hand-o-left" style="font-size: 10em;"></i>
                    <h5>Payable List</h5>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card">
            <div class="body text-center">
                <a href="/studentportal/studentsPayment/show" target="_blank">
                    <i class="fa fa-hand-o-right" style="font-size: 10em;"></i>
                    <h5>All Payments</h5>
                </a>
            </div>
        </div>
    </div> --}}
    </div>
</x-backend.layouts.master>